name: Trigger auto deployment for exploding-kittens

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/exploding-kittens-AutoDeployTrigger-5a881951-0431-4a3a-a3e9-563699d5c90c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.EXPLODINGKITTENS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EXPLODINGKITTENS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EXPLODINGKITTENS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: mapaille.azurecr.io
          registryUsername: ${{ secrets.EXPLODINGKITTENS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EXPLODINGKITTENS_REGISTRY_PASSWORD }}
          containerAppName: exploding-kittens
          resourceGroup: exploding-kittens
          dockerfilePath: Mapaille.ExplodingKittens.WebApp/Dockerfile
          imageToBuild: mapaille.azurecr.io/exploding-kittens:${{ github.sha }}
